In [ ]:
import pandas as pd
from scipy import stats

**Hypothesis Test 1**

In [ ]:
result_data = pd.read_csv('/content/drive/MyDrive/DSA210/Hypothesis_Test1.csv')
result_data.head(10)

,Unnamed: 0,raceId,year,round,circuitId,name,driverId,constructorId,positionOrder,laps,rank,statusId,stop,lap,duration
0,0,1166,2025,22,80,Las Vegas Grand Prix,830,9,1,50,1,1,1,25,21.708
1,1,1166,2025,22,80,Las Vegas Grand Prix,847,131,2,50,9,1,1,17,20.929
2,2,1166,2025,22,80,Las Vegas Grand Prix,863,131,3,50,2,1,1,2,21.968
3,3,1166,2025,22,80,Las Vegas Grand Prix,844,6,4,50,3,1,1,24,21.351
4,4,1166,2025,22,80,Las Vegas Grand Prix,832,3,5,50,4,1,1,22,21.164
5,5,1166,2025,22,80,Las Vegas Grand Prix,865,215,6,50,10,1,1,20,21.324
6,6,1166,2025,22,80,Las Vegas Grand Prix,807,15,7,50,8,1,1,30,22.333
7,7,1166,2025,22,80,Las Vegas Grand Prix,1,6,8,50,6,1,1,29,21.638
8,8,1166,2025,22,80,Las Vegas Grand Prix,839,210,9,50,7,1,1,27,22.389
9,9,1166,2025,22,80,Las Vegas Grand Prix,860,210,10,50,5,1,1,17,21.491

In [ ]:
hyp1 = result_data[['positionOrder', 'lap']]
hyp1.head(10)

   positionOrder  lap
0              1   25
1              2   17
2              3    2
3              4   24
4              5   22
5              6   20
6              7   30
7              8   29
8              9   27
9             10   17

In [ ]:
res = stats.spearmanr(hyp1['positionOrder'], hyp1['lap'])
print("P Value: ", res.pvalue)
print("Correlation: ", res.correlation)

P Value:  2.3260527360253857e-24
Correlation:  -0.12616286088928053

**Hypothesis Test 2**

In [ ]:
result_data1 = pd.read_csv('/content/drive/MyDrive/DSA210/Hypothesis_Test2.csv')
result_data1.head(10)

,Unnamed: 0,raceId,stop,year,circuitId,name,date,time,circuitRef,location,country,lat,lng,alt,temp
0,0,337,1.095238,2010,3,Bahrain Grand Prix,2010-03-14,12:00:00,bahrain,Sakhir,Bahrain,26.03250,50.510600,7,26.10
1,1,338,1.428571,2010,1,Australian Grand Prix,2010-03-28,6:00:00,albert_park,Melbourne,Australia,-37.84970,144.968000,10,20.65
2,2,339,1.150000,2010,2,Malaysian Grand Prix,2010-04-04,8:00:00,sepang,Sepang,Malaysia,2.76083,101.738000,18,29.90
3,3,340,2.567164,2010,17,Chinese Grand Prix,2010-04-18,6:00:00,shanghai,Shanghai,China,31.33890,121.220000,5,16.90
4,4,341,1.250000,2010,4,Spanish Grand Prix,2010-05-09,12:00:00,catalunya,Montmeló,Spain,41.57000,2.261110,109,15.60
5,5,343,1.185185,2010,5,Turkish Grand Prix,2010-05-30,11:00:00,istanbul,Istanbul,Turkey,40.95170,29.405000,130,25.60
6,6,345,1.241379,2010,12,European Grand Prix,2010-06-27,12:00:00,valencia,Valencia,Spain,39.45890,-0.331667,4,23.50
7,7,347,1.310345,2010,10,German Grand Prix,2010-07-25,12:00:00,hockenheimring,Hockenheim,Germany,49.32780,8.565830,103,17.40
8,8,348,1.120000,2010,11,Hungarian Grand Prix,2010-08-01,12:00:00,hungaroring,Budapest,Hungary,47.57890,19.248600,264,21.10
9,9,351,1.307692,2010,15,Singapore Grand Prix,2010-09-26,12:00:00,marina_bay,Singapore,Singapore,1.29140,103.864000,18,27.90

In [ ]:
res = stats.spearmanr(result_data1['temp'], result_data1['stop'])
print("P Value: ", res.pvalue)
print("Correlation: ", res.correlation)

P Value:  0.2737587919020263
Correlation:  -0.07550601598748641